const syllabus=[
 {title:'Quantitative Aptitude',items:['Number System - LCM/HCF, divisibility, remainders, factors','Percentages','Profit, Loss & Discount','Ratio, Proportion & Variation','Averages','Simple & Compound Interest','Time, Speed & Distance','Time & Work','Mixtures & Alligations','Permutations & Combinations, Probability','Simplification & Approximation','Algebra basics','Mensuration','Data Interpretation']},
 {title:'Logical Reasoning',items:['Coding-Decoding','Blood Relations','Direction Sense','Syllogisms','Seating Arrangement','Puzzles','Series','Analogy & Classification','Statement-Conclusion / Assumption','Venn Diagrams']},
 {title:'Verbal Reasoning / English',items:['Reading Comprehension','Sentence Correction / Error Spotting','Para Jumbles','Synonyms / Antonyms / Fill in the blanks','Critical Reasoning']}
];
const $=s=>document.querySelector(s),colors=['#b7d75e','#baaef6','#f5b381','#e9a9c0','#82c9bc'];
const defaults={tasks:['Morning revision','Practice questions','Mock test / review'],taskChecks:{},topicChecks:{},dsaTopics:[]};
let activeProfile=localStorage.getItem('focusFlowActiveProfile')||'me',activeMonth=new Date(),state;
activeMonth.setDate(1);
function stateKey(id=activeProfile){return `focusFlowProfile-${id}`}
function loadState(id=activeProfile){const saved=localStorage.getItem(stateKey(id));if(saved)return {...defaults,...JSON.parse(saved)};if(id==='me'){const legacyTasks=JSON.parse(localStorage.getItem('focusFlowTasks')||'null');return {tasks:legacyTasks||defaults.tasks,taskChecks:JSON.parse(localStorage.getItem('focusFlowTaskChecks')||'{}'),topicChecks:JSON.parse(localStorage.getItem('focusFlowTopics')||'{}'),dsaTopics:JSON.parse(localStorage.getItem('focusFlowDsaTopics')||'[]')}}return structuredClone(defaults)}
function save(){localStorage.setItem(stateKey(),JSON.stringify(state));syncCurrentProfile()}
function percent(profileState=state){let total=0,complete=0;syllabus.forEach((group,g)=>group.items.forEach((_,i)=>{total++;if(profileState.topicChecks[`${g}-${i}`])complete++}));return Math.round(complete/total*100)}
const monthKey=()=>`${activeMonth.getFullYear()}-${String(activeMonth.getMonth()+1).padStart(2,'0')}`;
const escapeHtml=s=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function renderTracker(){const days=new Date(activeMonth.getFullYear(),activeMonth.getMonth()+1,0).getDate(),root=$('#calendarTracker');root.style.setProperty('--days',days);$('#monthButton').textContent=activeMonth.toLocaleDateString(undefined,{month:'long',year:'numeric'});$('#monthInput').value=monthKey();let head='<div class="calendar-header"><div class="task-head">TASKS</div>';for(let d=1;d<=days;d++){const weekend=[0,6].includes(new Date(activeMonth.getFullYear(),activeMonth.getMonth(),d).getDay());head+=`<div class="${weekend?'weekend':''}">${d}</div>`}head+='<div>REMOVE</div></div>';const rows=state.tasks.map((task,i)=>{let daysHtml='';for(let d=1;d<=days;d++){const id=`${monthKey()}-${i}-${d}`;daysHtml+=`<input class="day-box" type="checkbox" data-task="${i}" data-day="${d}" ${state.taskChecks[id]?'checked':''} aria-label="${escapeHtml(task)}, day ${d}">`}return `<div class="task-row"><div class="task-label"><i class="task-color" style="background:${colors[i%colors.length]}"></i><span>${escapeHtml(task)}</span></div>${daysHtml}<button class="delete-task" data-delete="${i}">Delete</button></div>`}).join('');root.innerHTML=head+rows;document.querySelectorAll('.day-box').forEach(x=>x.onchange=e=>{state.taskChecks[`${monthKey()}-${e.target.dataset.task}-${e.target.dataset.day}`]=e.target.checked;save()});document.querySelectorAll('.delete-task').forEach(x=>x.onclick=()=>removeTask(+x.dataset.delete))}
function removeTask(index){state.tasks.splice(index,1);const updated={};for(const [id,value] of Object.entries(state.taskChecks)){const parts=id.split('-'),oldIndex=+parts[2];if(oldIndex===index)continue;parts[2]=String(oldIndex>index?oldIndex-1:oldIndex);updated[parts.join('-')]=value}state.taskChecks=updated;save();renderTracker()}
function renderTopics(){const root=$('#topicLists'),template=$('#topicTemplate');root.innerHTML='';syllabus.forEach((group,g)=>{const card=template.content.cloneNode(true);card.querySelector('.topic-number').textContent=g+1;card.querySelector('h3').textContent=group.title;card.querySelector('.topic-count').textContent=`${group.items.filter((_,i)=>state.topicChecks[`${g}-${i}`]).length} / ${group.items.length}`;card.querySelector('.topics').innerHTML=group.items.map((item,i)=>`<label class="topic-item"><input class="topic-check" type="checkbox" data-group="${g}" data-topic="${i}" ${state.topicChecks[`${g}-${i}`]?'checked':''}><span>${item}</span></label>`).join('');root.append(card)});document.querySelectorAll('.topic-check').forEach(x=>x.onchange=e=>{state.topicChecks[`${e.target.dataset.group}-${e.target.dataset.topic}`]=e.target.checked;save();renderTopics();renderScores()})}
function renderDsa(){const root=$('#dsaCapsules');root.innerHTML=state.dsaTopics.length?state.dsaTopics.map((topic,i)=>`<button class="dsa-capsule ${topic.done?'is-done':''}" data-dsa="${i}"><span class="capsule-check">${topic.done?'✓':''}</span>${escapeHtml(topic.name)}<span class="remove-dsa" data-remove-dsa="${i}">×</span></button>`).join(''):'<span class="empty-dsa">Add your first DSA topic to get started.</span>';document.querySelectorAll('[data-dsa]').forEach(x=>x.onclick=e=>{if(e.target.closest('[data-remove-dsa]'))return;state.dsaTopics[+x.dataset.dsa].done=!state.dsaTopics[+x.dataset.dsa].done;save();renderDsa()});document.querySelectorAll('[data-remove-dsa]').forEach(x=>x.onclick=e=>{e.stopPropagation();state.dsaTopics.splice(+x.dataset.removeDsa,1);save();renderDsa()})}
function addDsa(){const input=$('#newDsaTopic'),name=input.value.trim();if(name&&!state.dsaTopics.some(x=>x.name.toLowerCase()===name.toLowerCase())){state.dsaTopics.push({name,done:false});input.value='';save();renderDsa()}input.focus()}
function renderScores(){const me=loadState('me'),friend=loadState('friend');$('#meScore').textContent=`${percent(me)}%`;$('#friendScore').textContent=`${percent(friend)}%`;$('#overallProgress').textContent=`${percent()}% complete`;$('#activeProfileName').textContent=activeProfile==='me'?"Y's":"K's";document.querySelectorAll('[data-profile]').forEach(x=>x.classList.toggle('active',x.dataset.profile===activeProfile))}
function renderAll(){renderTracker();renderTopics();renderDsa();renderScores()}
function switchProfile(id){if(id===activeProfile)return;activeProfile=id;localStorage.setItem('focusFlowActiveProfile',id);state=loadState();renderAll();pullProfiles()}
function shiftMonth(amount){activeMonth.setMonth(activeMonth.getMonth()+amount);renderTracker()}
const config=window.FOCUS_FLOW_SUPABASE||{};
function syncingEnabled(){return config.url&&config.anonKey&&config.pairCode}
async function supabaseRequest(path,options={}){return fetch(`${config.url}/rest/v1/${path}`,{...options,headers:{apikey:config.anonKey,Authorization:`Bearer ${config.anonKey}`,"Content-Type":"application/json",Prefer:'return=representation',...(options.headers||{})}})}
async function syncCurrentProfile(){if(!syncingEnabled())return;try{const response=await supabaseRequest('focus_flow_profiles?on_conflict=pair_code,profile_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({pair_code:config.pairCode,profile_id:activeProfile,state,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error(await response.text());$('#syncStatus').textContent='Synced with your study buddy'}catch(error){$('#syncStatus').textContent='Sync failed - check Supabase table setup';console.error('Focus Flow sync error:',error)}}
async function pullProfiles(){if(!syncingEnabled())return;try{const filter=new URLSearchParams({pair_code:`eq.${JSON.stringify(config.pairCode)}`}).toString();const r=await supabaseRequest(`focus_flow_profiles?${filter}`);if(!r.ok)throw new Error('Unable to read shared profiles');const data=await r.json(),activeRow=data.find(row=>row.profile_id===activeProfile);if(activeRow){data.forEach(row=>localStorage.setItem(stateKey(row.profile_id),JSON.stringify({...defaults,...row.state})));state=loadState();renderAll();$('#syncStatus').textContent='Synced with your study buddy'}else{await syncCurrentProfile();$('#syncStatus').textContent='Your tracker is now shared with your study buddy'}}catch(error){$('#syncStatus').textContent='Sync paused - check Supabase setup';console.error('Focus Flow read error:',error)}}
$('#prevMonth').onclick=()=>shiftMonth(-1);$('#nextMonth').onclick=()=>shiftMonth(1);$('#monthButton').onclick=()=>$('#monthInput').showPicker();$('#monthInput').onchange=e=>{const [y,m]=e.target.value.split('-');activeMonth=new Date(+y,+m-1,1);renderTracker()};$('#addTask').onclick=()=>{const input=$('#newTask'),value=input.value.trim();if(value&&!state.tasks.includes(value)){state.tasks.push(value);input.value='';save();renderTracker()}};$('#newTask').onkeydown=e=>{if(e.key==='Enter')$('#addTask').click()};$('#openDsaInput').onclick=()=>{const entry=$('#dsaEntry');entry.classList.toggle('visible');if(entry.classList.contains('visible'))$('#newDsaTopic').focus()};$('#addDsaTopic').onclick=addDsa;$('#newDsaTopic').onkeydown=e=>{if(e.key==='Enter')addDsa()};document.querySelectorAll('[data-profile]').forEach(x=>x.onclick=()=>switchProfile(x.dataset.profile));$('#syncNow').onclick=()=>pullProfiles();$('#todayLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'});state=loadState();renderAll();pullProfiles();if(syncingEnabled())setInterval(pullProfiles,30000);
